export const authLocalization = {
    account: "Account",
    addAccount: "Add Account",
    alreadyHaveAnAccount: "Already have an account?",
    avatar: "Avatar",
    avatarDescription: "Click on the avatar to upload a custom one from your files.",
    avatarInstructions: "An avatar is optional but strongly recommended.",
    changePassword: "Change Password",
    changePasswordDescription: "Enter your current password and a new password.",
    changePasswordInstructions: "Please use 8 characters at minimum.",
    changePasswordSuccess: "Your password has been changed.",
    currentPassword: "Current Password",
    currentPasswordPlaceholder: "Current Password",
    currentSession: "Current Session",
    deleteAccount: "Delete Account",
    deleteAccountDescription: "Permanently remove your account and all of its contents. This action is not reversible, so please continue with caution.",
    deleteAccountInstructions: "Please confirm the deletion of your account. This action is not reversible, so please continue with caution.",
    deleteAccountEmail: "Please check your email to verify the deletion of your account.",
    deleteAccountSuccess: "Your account has been deleted.",
    deleteAccountNotFresh: "You must be recently logged in to delete your account.",
    disabledCredentialsDescription: "Choose a provider to login to your account",
    dontHaveAnAccount: "Don't have an account?",
    email: "Email",
    emailDescription: "Enter the email address you want to use to log in.",
    emailInstructions: "Please use a valid email address.",
    emailPlaceholder: "m@example.com",
    emailVerifyChange: "Please check your email to verify the change.",
    emailVerification: "Please check your email for the verification link.",
    forgotPassword: "Forgot Password",
    forgotPasswordAction: "Send reset link",
    forgotPasswordDescription: "Enter your email to reset your password",
    forgotPasswordEmail: "Check your email for the password reset link.",
    forgotPasswordLink: "Forgot your password?",
    link: "Link",
    magicLink: "Magic Link",
    magicLinkAction: "Send magic link",
    magicLinkDescription: "Enter your email to receive a magic link",
    magicLinkEmail: "Check your email for the magic link",
    name: "Name",
    nameDescription: "Please enter your full name, or a display name.",
    nameInstructions: "Please use 32 characters at maximum.",
    namePlaceholder: "Name",
    newPassword: "New Password",
    newPasswordPlaceholder: "New Password",
    passkey: "Passkey",
    password: "Password",
    passwordDescription: "Enter your current password.",
    passwordInstructions: "Please use 8 characters at minimum.",
    passwordPlaceholder: "Password",
    providers: "Providers",
    providersDescription: "Connect your account with a third-party service.",
    providerLinkSuccess: "Provider linked successfully.",
    providerUnlinkSuccess: "Provider unlinked successfully.",
    providersLoadingError: "Could not load account info",
    rememberMe: "Remember me",
    resetPassword: "Reset Password",
    resetPasswordAction: "Save new password",
    resetPasswordDescription: "Enter your new password below",
    resetPasswordInvalidToken: "Invalid reset password link",
    resetPasswordSuccess: "Password reset successfully",
    revoke: "Revoke",
    signIn: "Sign In",
    signInAction: "Login",
    signInDescription: "Enter your email below to login to your account",
    signInUsernameDescription: "Enter your username below to login to your account",
    signInWith: "Sign in with",
    signOut: "Sign Out",
    signUp: "Sign Up",
    signUpAction: "Create an account",
    signUpDescription: "Enter your information to create an account",
    signUpEmail: "Check your email for the verification link.",
    sessions: "Sessions",
    sessionsDescription: "Manage your active sessions and revoke access.",
    setPasswordDescription: "You registered with a third-party service. Click the button below to set a password for your account.",
    setPassword: "Set Password",
    setPasswordEmailSent: "Check your email to set your password.",
    settings: "Settings",
    save: "Save",
    unlink: "Unlink",
    username: "Username",
    usernameDescription: "Enter the username you want to use to log in.",
    usernameInstructions: "Please use 32 characters at maximum.",
    usernamePlaceholder: "Username",
    usernameSignInPlaceholder: "Username or email",
}

export type AuthLocalization = typeof authLocalization